<template>
  <el-card>
    <template #header>
      <div class="flex justify-between items-center">
        <span class="font-bold text-lg">Slow-Live Camera Presets</span>
        <el-button type="primary" @click="openPreset('create')">+ New Preset</el-button>
      </div>
    </template>
    <el-alert type="info" show-icon :closable="false" class="mb-3">
      RTMP URLs auto-generated by backend. Cover image upload is optional — if not set, frontend uses default frame.
      <strong class="ml-2 text-amber-700">Note:</strong> Location field will be auto-sanitized to prefecture level on public API. Do NOT enter exact village/coordinates here.
    </el-alert>

    <el-table :data="list" stripe>
      <el-table-column label="Cover" width="100">
        <template #default="{ row }">
          <el-image v-if="row.cover_image" :src="resolveUrl(row.cover_image)" fit="cover"
                   style="width:72px;height:44px;border-radius:2px;border:1px solid #e5e7eb" />
          <div v-else class="w-[72px] h-[44px] bg-slate-100 flex items-center justify-center text-slate-300 text-[10px]">—</div>
        </template>
      </el-table-column>
      <el-table-column prop="name" label="Name" width="220" />
      <el-table-column prop="location" label="Location" width="160" />
      <el-table-column prop="description" label="Description" show-overflow-tooltip />
      <el-table-column prop="status" label="Status" width="110">
        <template #default="{ row }">
          <el-tag :type="row.status === 'live' ? 'danger' : 'info'" effect="dark" size="small">
            <span v-if="row.status === 'live'" class="flex items-center gap-1"><span class="w-1.5 h-1.5 rounded-full bg-white animate-pulse"></span>LIVE</span>
            <span v-else>{{ row.status }}</span>
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="Push Key" min-width="220">
        <template #default="{ row }">
          <code class="text-xs text-slate-600 break-all">{{ row.camera_rtmp_url || '—' }}</code>
        </template>
      </el-table-column>
      <el-table-column label="Actions" width="300">
        <template #default="{ row }">
          <el-button v-if="row.status !== 'live'" size="small" type="success" @click="enable(row.id)">Enable</el-button>
          <el-button v-else size="small" @click="disable(row.id)">Stop</el-button>
          <el-button size="small" @click="copyKey(row)">Copy Key</el-button>
          <el-button size="small" @click="openPreset('edit', row)">Edit</el-button>
          <el-button size="small" type="danger" @click="del(row.id)">Del</el-button>
        </template>
      </el-table-column>
    </el-table>
  </el-card>

  <!-- Create / Edit Dialog -->
  <el-dialog v-model="open" :title="isEditing ? 'Edit Slow-Live Preset' : 'New Slow-Live Preset'" width="560px">
    <el-form :model="form" label-width="120px">
      <el-form-item label="Name">
        <el-input v-model="form.name" placeholder="云雾茶区 · 临沧" />
      </el-form-item>
      <el-form-item label="Location">
        <el-input v-model="form.location" placeholder="云南省 · 临沧市" />
        <div class="text-[11px] text-amber-600 mt-1">
          ⚠ 请勿填写具体村/乡/坐标。此值将在 public API 自动脱敏到"市/州"级。
        </div>
      </el-form-item>
      <el-form-item label="Description">
        <el-input v-model="form.description" type="textarea" :rows="2" placeholder="茶园简要描述（内部用）" />
      </el-form-item>

      <!-- Cover Image Upload -->
      <el-form-item label="Cover Image">
        <div class="flex items-start gap-4">
          <!-- 预览 -->
          <div v-if="form.cover_image" class="relative">
            <el-image :src="resolveUrl(form.cover_image)" fit="cover"
                     style="width:160px;height:100px;border-radius:2px;border:1px solid #e5e7eb" />
            <button type="button" @click="form.cover_image = ''"
                    class="absolute -top-2 -right-2 w-6 h-6 bg-red-500 text-white rounded-full text-xs flex items-center justify-center hover:bg-red-600">×</button>
          </div>
          <!-- 上传按钮 -->
          <el-upload
            :show-file-list="false"
            :before-upload="() => false"
            :auto-upload="false"
            accept="image/jpeg,image/png,image/webp"
            :disabled="uploading"
          >
            <el-button type="primary" plain size="small">
              <span v-if="uploading">Uploading…</span>
              <span v-else>{{ form.cover_image ? 'Replace Image' : 'Upload Cover' }}</span>
            </el-button>
            <template #tip>
              <div class="text-[11px] text-slate-400 mt-1">JPG/PNG/WEBP · max 10MB · 推荐 16:10 · 800×500</div>
            </template>
          </el-upload>
          <input ref="coverFileRef" type="file" accept="image/jpeg,image/png,image/webp" class="hidden"
                 @change="onCoverFileChange" />
          <el-button v-if="!form.cover_image && !uploading" size="small" @click="triggerFile(coverFileRef)">选择文件</el-button>
        </div>
      </el-form-item>

      <el-form-item>
        <div class="text-xs text-slate-400">
          Push Source: <code>camera_rtmp</code> (auto) · RTMP URL/Key generated on server after enable.
        </div>
      </el-form-item>
    </el-form>
    <template #footer>
      <el-button @click="open = false">Cancel</el-button>
      <el-button type="primary" :loading="saving" @click="save">{{ isEditing ? 'Save Changes' : 'Create Preset' }}</el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { onMounted, ref, reactive, computed } from 'vue'
import { ElMessage } from 'element-plus'
import { api, upload } from '@/api/client'

const list = ref<any[]>([])
const open = ref(false)
const isEditing = ref(false)
const editingId = ref<number | null>(null)
const uploading = ref(false)
const saving = ref(false)
const coverFileRef = ref<any>(null)

function triggerFile(ref: any) { ref?.click() }
const form = reactive({ name: '', location: '', description: '', cover_image: '' })

// 后端出参 cover_image 存的是相对路径 /uploads/image/xxx.jpg
// admin 页面直接拼 baseURL 显示
function resolveUrl(url: string): string {
  if (!url) return ''
  if (url.startsWith('http')) return url
  const base = (import.meta.env.VITE_API_BASE || '').replace(/\/api\/v1$/, '')
  return base + url
}

async function load() {
  try { const d: any = await api.get('/slow-presets'); list.value = d?.items || d || [] } catch {}
}
onMounted(load)

function openPreset(mode: 'create' | 'edit', row?: any) {
  if (mode === 'edit' && row) {
    isEditing.value = true
    editingId.value = row.id
    Object.assign(form, {
      name: row.name,
      location: row.location,
      description: row.description,
      cover_image: row.cover_image || ''
    })
  } else {
    isEditing.value = false
    editingId.value = null
    Object.assign(form, { name: '', location: '', description: '', cover_image: '' })
  }
  open.value = true
}

async function onCoverFileChange(e: Event) {
  const input = e.target as HTMLInputElement
  const file = input.files?.[0]
  if (!file) return
  uploading.value = true
  try {
    const url = await upload(file, 'image')
    form.cover_image = url
    ElMessage.success('Cover uploaded')
  } catch (err: any) {
    ElMessage.error(`Upload failed: ${err?.message || err}`)
  } finally {
    uploading.value = false
    input.value = ''
  }
}

async function save() {
  saving.value = true
  try {
    if (isEditing.value && editingId.value) {
      await api.put(`/slow-presets/${editingId.value}`, { ...form })
      ElMessage.success('Updated')
    } else {
      await api.post('/slow-presets', {
        ...form,
        push_source: 'camera_rtmp',
        room_type: 'slow_preset',
        cover_image: form.cover_image
      })
      ElMessage.success('Created')
    }
    open.value = false
    load()
  } catch (err: any) {
    ElMessage.error(err?.message || 'Save failed')
  } finally {
    saving.value = false
  }
}

async function enable(id: number) { await api.post(`/slow-presets/${id}/enable`); ElMessage.success('Streaming'); load() }
async function disable(id: number) { await api.post(`/slow-presets/${id}/disable`); ElMessage.success('Stopped'); load() }
async function del(id: number) { await api.delete(`/slow-presets/${id}`); load() }
function copyKey(row: any) {
  const u = row.camera_rtmp_url || ''
  if (u) { navigator.clipboard.writeText(u); ElMessage.success('Key copied') }
  else ElMessage.info('URL not ready yet')
}
</script>
