<template>
  <el-card>
    <template #header>
      <div class="flex justify-between items-center">
        <span class="font-bold text-lg">🌱 24/7 Slow-Live Camera Presets</span>
        <el-button type="primary" @click="open = true">+ New Preset</el-button>
      </div>
    </template>
    <el-alert title="RTMP URLs are auto-generated by the backend. Push key is shown below." type="info" show-icon :closable="false" class="mb-3" />
    <el-table :data="list" stripe>
      <el-table-column prop="name" label="Name" width="200" />
      <el-table-column prop="location" label="Location" width="160" />
      <el-table-column prop="description" label="Description" show-overflow-tooltip />
      <el-table-column prop="status" label="Status" width="110">
        <template #default="{ row }">
          <el-tag :type="row.status === 'live' ? 'danger' : 'info'" effect="dark">
            <span v-if="row.status === 'live'" class="flex items-center gap-1"><span class="w-1.5 h-1.5 rounded-full bg-white animate-pulse"></span>LIVE</span>
            <span v-else>{{ row.status }}</span>
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="Push Key" min-width="220">
        <template #default="{ row }">
          <code class="text-xs text-slate-600">{{ (row.camera_rtmp_url || '—').slice(0, 60) }}…</code>
        </template>
      </el-table-column>
      <el-table-column label="Actions" width="280">
        <template #default="{ row }">
          <el-button v-if="row.status !== 'live'" size="small" type="success" @click="enable(row.id)">▶ Enable</el-button>
          <el-button v-else size="small" @click="disable(row.id)">⏸ Stop</el-button>
          <el-button size="small" @click="copyKey(row)">Copy Key</el-button>
          <el-button size="small" type="danger" @click="del(row.id)">Del</el-button>
        </template>
      </el-table-column>
    </el-table>
  </el-card>

  <el-dialog v-model="open" title="New Slow-Live Preset" width="480px">
    <el-form :model="form" label-width="120px">
      <el-form-item label="Name"><el-input v-model="form.name" placeholder="云南省临沧市临翔区邦东乡曼岗村茶园" /></el-form-item>
      <el-form-item label="Location"><el-input v-model="form.location" placeholder="临沧市曼岗村" /></el-form-item>
      <el-form-item label="Description"><el-input v-model="form.description" type="textarea" /></el-form-item>
      <el-form-item>
        <div class="text-xs text-gray-400">
          Push Source: <code>camera_rtmp</code> (auto-selected) — RTMP URL/Key generated on server.
        </div>
      </el-form-item>
    </el-form>
    <template #footer>
      <el-button @click="open = false">Cancel</el-button>
      <el-button type="primary" @click="save">Create Preset</el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { onMounted, ref, reactive } from 'vue'
import { ElMessage } from 'element-plus'
import { api } from '@/api/client'

const list = ref<any[]>([])
const open = ref(false)
// camera_rtmp_url 由后端自动生成，前端不填
const form = reactive({ name: '', location: '', description: '' })

async function load() {
  try { const d: any = await api.get('/slow-presets'); list.value = d?.items || d || [] } catch {}
}
onMounted(load)

async function save() {
  await api.post('/slow-presets', { ...form, push_source: 'camera_rtmp', room_type: 'slow_preset' })
  ElMessage.success('Created')
  open.value = false
  load()
}
async function enable(id: number) { await api.post(`/slow-presets/${id}/enable`); ElMessage.success('Streaming'); load() }
async function disable(id: number) { await api.post(`/slow-presets/${id}/disable`); ElMessage.success('Stopped'); load() }
async function del(id: number) { await api.delete(`/slow-presets/${id}`); load() }
function copyKey(row: any) {
  const u = row.camera_rtmp_url || ''
  if (u) { navigator.clipboard.writeText(u); ElMessage.success('Key copied') }
  else ElMessage.info('URL not ready yet')
}
</script>
